apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tournament-service-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: tournament-service.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tournament-service
            port:
              number: 8002
